#!/bin/bash

clear

if [[ -d $1 && -d $2 ]]; then
    printf "\n check input : $1 & $2 is a directory\n"
elif [[ -f $1 && -f $2 ]]; then
    printf "\n check input : $1 & $2 is a file\n"
else
    printf "\n USE: $0 original new (optional: patchfilename)"
    printf "\n do not mix files & folders\n\n"
    exit 1
fi

if [ -z "$3" ]
then
    tfile1="$(mktemp XXXXXX)"
    printf "\n -> create $tfile1.patch \n"
else
    printf "\n -> create $3.patch \n"
    tfile1="$3"
fi

tfile2="$(mktemp XXXXXX)"

printf "\n  START\n =======\n"
printf " 1. DIFF $1 $2\n"

diff -u -r -d -B -N     \
    --exclude="*~"      \
    --exclude=".svn"    \
    --exclude=".git"    \
    --exclude="*.zip*"  \
    --exclude="*.gz"    \
    --exclude="*.tar"   \
    --exclude="*.patch" \
    --exclude="*.bak"   \
    --exclude="*.old"   \
    --exclude="*.o"     \
    $1 $2 >$tfile1

printf " 2. GREP $tfile2\n"
grep '^[^\diff]' $tfile1 >$tfile2

printf " 3. SED  $tfile2\n"
sed -i "s@+++ $2@+++ $1@g" "$tfile2"

printf " 4. CLEAN $tfile2 $tfile1\n"
rm $tfile1
if [ ! -f "$1.patch" ]
then
    mv $tfile2 $1.patch
    printf " 5. DONE $1.patch\n\n"
else
    mv $tfile2 $tfile1.patch
    printf " 5. DONE $tfile2.patch\n\n"
fi

